### PR TITLE
Handle microseconds from redshift

### LINKED ISSUE #35: Getting `DateTimeParseException` error while reading from redshift timestamp.
```
java.time.format.DateTimeParseException: Text '2015-11-07 05:16:40.16858' could not be parsed, unparsed text found at index 23
```

### PR DESCRIPTION
**Pull request by lucagiovagnoli**
Handling microseconds (6 digits after the comma).
Fixes #35 and #48

### CODE REVIEW

**Comment by lucagiovagnoli** [comment]
Wondering if we should change the [Writer](https://github.com/spark-redshift-community/spark-redshift/blob/master/src/main/scala/io/github/spark_redshift_community/spark/redshift/RedshiftWriter.scala#L231) too? I'm not sure if microseconds is always desirable or if we should parametrize that somehow. We can also leave as is for now. @smoy

File: src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala [hunk 1]
```diff
@@ -37,7 +37,8 @@ private[redshift] object Conversions {
     * "A formatter created from a pattern can be used as many times as necessary,
     * it is immutable and is thread-safe."
     */
-  private val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss[.SSS][.SS][.S][X]")
+  private val formatter = DateTimeFormatter.ofPattern(
+    "yyyy-MM-dd HH:mm:ss[.SSSSSS][.SSS][.SS][.S][X]")
```
Comment (eeshugerman) [inline src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala]: I think `[.SSSS]` and `[.SSSSS]` are needed too, since Redshift timestamps can have any number of decimal places:
```
> select '2019-01-01 00:00:00.0001' :: timestamp                                                                                                                                                                              
+--------------------------+
| timestamp                |
|--------------------------|
| 2019-01-01 00:00:00.0001 |
+--------------------------+
```
I tried this in an `unload` and the format was the same in the file on S3.

File: src/test/scala/io/github/spark_redshift_community/spark/redshift/TestUtils.scala [hunk 2]
```diff
@@ -94,6 +94,29 @@ object TestUtils {
...
+        date,
+        hour,
+        minutes,
+        seconds
+      )
+    )
+    ts.setNanos(nanos)
+    ts
+  }
+
```
Comment (eeshugerman) [inline src/test/scala/io/github/spark_redshift_community/spark/redshift/TestUtils.scala]: Redshift doesn't support anything past microseconds, so I'd say no reason to test nanos.

Comment (eeshugerman) [reply src/test/scala/io/github/spark_redshift_community/spark/redshift/TestUtils.scala]:
```
> select '2019-01-01 00:00:00.000001' :: timestamp           -- microsecond                                                                                                                                                               
+----------------------------+
| timestamp                  |
|----------------------------|
| 2019-01-01 00:00:00.000001 |
+----------------------------+

> select '2019-01-01 00:00:00.0000001' :: timestamp          -- tenth of a microsecond gets truncated                                                                                                                                                 
+---------------------+
| timestamp           |
|---------------------|
| 2019-01-01 00:00:00 |
+---------------------+
```

File: src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala (hunk 1 above)
Comment (lucagiovagnoli) [reply src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala]: Right, I'll add them, thanks for pointing this out

File: src/test/scala/io/github/spark_redshift_community/spark/redshift/TestUtils.scala (hunk 2 above)
Comment (lucagiovagnoli) [reply src/test/scala/io/github/spark_redshift_community/spark/redshift/TestUtils.scala]: I am not testing nanos here.
The Timestamp object has only a `.setNanos()` method and I can only use that to set microseconds. If you check the test, I am doing `nanos=123456000` that is equivalent to have 123456 microseconds

**Comment by lucagiovagnoli** [comment]
@mschmo thanks for reviewing and approving!
@dichiarafrancesco or @smoy  can I get an approval/shipit by one of you with write access please ?

**Comment by lucagiovagnoli** [comment]
This was released: https://oss.sonatype.org/#nexus-search;quick~spark-redshift-community
