### PR TITLE
Modernize datetime parsing - use DateTimeFormatter from Java 8

### LINKED ISSUE #25: Bug in parsing timestamptz
I believe the following error is encountered when parsing the timestamptz (timestamp with timezone) from Redshift.

```Py4JJavaError: An error occurred while calling o227.collectToPython.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 4 times, most recent failure: Lost task 0.3 in stage 1.0 (TID 323, 10-81-19-120-uswest2adevc.dev.yelpcorp.com, executor 1): java.lang.NumberFormatException: For input string: "29+00"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.sql.Timestamp.valueOf(Timestamp.java:259)
	at io.github.spark_redshift_community.spark.redshift.Conversions$$anonfun$1$$anonfun$apply$11.apply(Conversions.scala:107)
	at io.github.spark_redshift_community.spark.redshift.Conversions$$anonfun$1$$anonfun$apply$11.apply(Conversions.scala:107)
	at io.github.spark_redshift_community.spark.redshift.Conversions$$anonfun$createRowConverter$1.apply(Conversions.scala:127)
	at io.github.spark_redshift_community.spark.redshift.Conversions$$anonfun$createRowConverter$1.apply(Conversions.scala:115)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.next(FileScanRDD.scala:104)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1889)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1877)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1876)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1876)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2110)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2059)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2048)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:365)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
	at org.apache.spark.sql.Dataset$$anonfun$collectToPython$1.apply(Dataset.scala:3257)
	at org.apache.spark.sql.Dataset$$anonfun$collectToPython$1.apply(Dataset.scala:3254)
	at org.apache.spark.sql.Dataset$$anonfun$53.apply(Dataset.scala:3364)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3363)
	at org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:3254)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NumberFormatException: For input string: "29+00"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at java.sql.Timestamp.valueOf(Timestamp.java:259)
	at io.github.spark_redshift_community.spark.redshift.Conversions$$anonfun$1$$anonfun$apply$11.apply(Conversions.scala:107)
	at io.github.spark_redshift_community.spark.redshift.Conversions$$anonfun$1$$anonfun$apply$11.apply(Conversions.scala:107)
	at io.github.spark_redshift_community.spark.redshift.Conversions$$anonfun$createRowConverter$1.apply(Conversions.scala:127)
	at io.github.spark_redshift_community.spark.redshift.Conversions$$anonfun$createRowConverter$1.apply(Conversions.scala:115)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:410)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.next(FileScanRDD.scala:104)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:255)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:247)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:836)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

### PR DESCRIPTION
**Pull request by lucagiovagnoli**
Fixes #25 

DateTimeFormatter is the Java 8 better version of SimpleDateFormat. It allows optional parsing args and many nice things, like it's immutable and thread-safe.

For review @davidmarin @smoy @dichiarafrancesco

### CODE REVIEW

File: src/test/scala/io/github/spark_redshift_community/spark/redshift/ConversionsSuite.scala [hunk 1]
```diff
@@ -58,6 +58,20 @@ class ConversionsSuite extends FunSuite {
     assert(convertedRow == expectedRow)
   }
 
+  test("Regression test for parsing timestamptz (bug #25 in spark_redshift_community)") {
+    val rowConverter = createRowConverter(
+      StructType(Seq(StructField("timestampWithTimezone", TimestampType))))
+
+    val timestampWithTimezone = "2014-03-01 00:00:01.123 -0300"
+    val expectedTimestampWithTimezoneMillis = TestUtils.toMillis(
```
Comment (smoy) [inline src/test/scala/io/github/spark_redshift_community/spark/redshift/ConversionsSuite.scala]: I am confused on this test case. The test input is "2014-03-01 00:00:01.123 -0300", the expected value is 2014-02-01 00:00:01.123. How is the expected value computing its associated timezone or is it utc based. The test input and expected is different at the month component... I am confused.

File: src/test/scala/io/github/spark_redshift_community/spark/redshift/ConversionsSuite.scala [hunk 2]
```diff
@@ -58,6 +58,20 @@ class ConversionsSuite extends FunSuite {
...
+      2014, 2, 1, 0, 0, 1, 123)
+
+    val convertedRow = rowConverter(Array(timestampWithTimezone))
+    val expectedRow = Row(new Timestamp(expectedTimestampWithTimezoneMillis))
+
+    assert(convertedRow == expectedRow)
+  }
```
Comment (smoy) [inline src/test/scala/io/github/spark_redshift_community/spark/redshift/ConversionsSuite.scala]: Can we further add a test case to cover the Catch clause that handles the input without timezone data?

File: src/test/scala/io/github/spark_redshift_community/spark/redshift/ConversionsSuite.scala (hunk 1 above)
Comment (lucagiovagnoli) [reply src/test/scala/io/github/spark_redshift_community/spark/redshift/ConversionsSuite.scala]: That month must have been a typo, check more recent revisions. On the other end, I think I was ignoring timezones completely in that revision..

I initially had a look at snowflake and they are using the old questionable SimpleDateFormat (for compatibility with java 6). See https://github.com/snowflakedb/spark-snowflake/blob/0503429a82f7e1a201b82beb564e056ab3d9814e/src/test/scala/net/snowflake/spark/snowflake/ConversionsSuite.scala#L42

I don't understand why they seem to disregard completely the timezone information (see tests with or without are the same). Then I noticed that for timestamptz Redshift seems to return a corresponding datetime str with the timezone always set to +00 (the string will be 'shifted' accordingly and correctly).  So they are probably ignoring that +00 but it doesn't look like proper timezone handling?

I'm now using DateTimeFormatter from java 8 and in the latest commit I think I convert from ZonedDateTime to -> timestamp correctly.

File: src/test/scala/io/github/spark_redshift_community/spark/redshift/ConversionsSuite.scala (hunk 2 above)
Comment (lucagiovagnoli) [reply src/test/scala/io/github/spark_redshift_community/spark/redshift/ConversionsSuite.scala]: We already do have that test for all normal timestamps (we've always had it). Please check line 45 in the ConversionSuite: https://github.com/spark-redshift-community/spark-redshift/blob/master/src/test/scala/io/github/spark_redshift_community/spark/redshift/ConversionsSuite.scala#L45

I've also tested the latest revision up to our python layer internally and timestamptz parsing works (scroll right):
```
+--------+--------+----------+-----------------+---------+-------+----------------+---------+-------------+--------------------+--------------------+
|testbyte|testbool|  testdate|       testdouble|testfloat|testint|        testlong|testshort|   teststring|       testtimestamp|     testtimestamptz|
+--------+--------+----------+-----------------+---------+-------+----------------+---------+-------------+--------------------+--------------------+
|    null|    null|      null|             null|     null|   null|            null|     null|         null|                null|                null|
|       0|    null|2015-07-03|              0.0|     -1.0|4141214|1239012341823719|     null|            f| 2015-07-03 00:00:00| 2015-07-03 03:00:00|
|       0|   false|      null|-1234152.12312498| 100000.0|   null|1239012341823719|       24|     ___|_123|                null|                null|
|       1|   false|2015-07-02|              0.0|      0.0|     42|1239012341823719|      -13|         asdf| 2015-07-02 00:00:00| 2015-07-02 04:00:00|
|       1|    true|2015-07-01| 1234152.12312498|      1.0|     42|1239012341823719|       23|Unicode's樂趣|2015-07-01 00:00:...|2015-07-01 05:00:...|
+--------+--------+----------+-----------------+---------+-------+----------------+---------+-------------+--------------------+--------------------+
```

File: src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala [hunk 3]
```diff
@@ -73,6 +82,20 @@ private[redshift] object Conversions {
...
+    val temporalAccessor = formatter.parse(s)
+
+    try {
+      // timestamptz
+      Timestamp.from(ZonedDateTime.from(temporalAccessor).toInstant)
+    }
+    catch {
+      // Case timestamp without timezone
+      case e: DateTimeException =>
+        Timestamp.valueOf(LocalDateTime.from(temporalAccessor))
```
Comment (smoy) [inline src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala]: I am uncertain of this behavior because LocalDateTime will influence by the Spark local timezone setting. When Redshift only has timestamp (within timezone data). 

https://docs.aws.amazon.com/redshift/latest/dg/r_Datetime_types.html

Redshift docs says, "By default, TIMESTAMP values are Coordinated Universal Time (UTC) in both user tables and Amazon Redshift system tables."

File: src/test/scala/io/github/spark_redshift_community/spark/redshift/ConversionsSuite.scala (hunk 1 above)
Comment (smoy) [reply src/test/scala/io/github/spark_redshift_community/spark/redshift/ConversionsSuite.scala]: Reading through Redshift documentation

https://docs.aws.amazon.com/redshift/latest/dg/r_Datetime_types.html#r_Datetime_types-timestamptz

```TIMESTAMPTZ values are UTC in user tables.```

How I understand it is that when one unloads the data, the text string having something like "2001-02-17 03:38:40+00" means this column is timestampz but the bare value is already in UTC. thus +00.

File: src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala (hunk 3 above)
Comment (smoy) [reply src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala]: never mind, i thought LocalDateTime just use the local timezone data from the machine. The class is defined as "This class does not store or represent a time-zone. "

File: src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala [hunk 4]
```diff
@@ -30,6 +32,13 @@ import org.apache.spark.sql.types._
  */
 private[redshift] object Conversions {
 
+  /**
+    * From the DateTimeFormatter docs (Java 8):
+    * "A formatter created from a pattern can be used as many times as necessary,
+    * it is immutable and is thread-safe."
+    */
+  private val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss[.SSS][.SS][.S][X]")
```
Comment (amoussawi) [inline src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala]: There could be more than 3 `S` here, it's causing errors in cases like `2018-05-03 06:23:33.081834+00`

Comment (lucagiovagnoli) [reply src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala]: The backend uses [Calendar](https://docs.oracle.com/javase/8/docs/api/java/util/Calendar.html#MILLISECOND), which won't go beyond milliseconds. Most of spark-redshift code is meant (and tested) not to go beyond milliseconds: https://github.com/spark-redshift-community/spark-redshift/blob/master/src/test/scala/io/github/spark_redshift_community/spark/redshift/ConversionsSuite.scala#L48

Comment (amoussawi) [reply src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala]: But it did in my case. I had to change the fetched format in my case as a quick fix.

Comment (lucagiovagnoli) [reply src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala]: You mean, you changed the format of your columns ?
Let me know if you'd like to take a crack at this to fix #35

Comment (amoussawi) [reply src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala]: Yes I had the change the format of my columns.
I can help with a fix, but I'm really not familiar with best practices here, if adding more `S` here fixes it then fine.

Comment (lucagiovagnoli) [reply src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala]: That's not enough. The backend needs to upgrade to something else than the [Calendar](https://docs.oracle.com/javase/8/docs/api/java/util/Calendar.html#MILLISECOND) library or we'll stay limited to milliseconds. So it requires a backend library change plus updating the string format.

Comment (amoussawi) [reply src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala]: It was working fine with databricks spark-redshift 3.0.0-preview

Comment (amoussawi) [reply src/main/scala/io/github/spark_redshift_community/spark/redshift/Conversions.scala]: maybe we can truncate to 3 digits, and show a warning (notice) about that and avoid an exception
